services:
    analytics-backend:
        container_name: analytics-backend
        depends_on:
            - analytics-elasticsearch
        environment:
            - JAVA_OPTS=-Xms2048m -Xmx4096m -XX:MaxMetaspaceSize=512m # increase Xmx in case of out of memory
            - LCP_ENGINE_ELASTICSEARCH_SERVER_IP=analytics-elasticsearch
            - LCP_PROJECT_ID=local
            - OSB_ASAH_BACKEND_ADMIN_REST_CONTROLLER_ENABLED=true
            - OSB_ASAH_BACKEND_URL=http://localhost:8082
            - OSB_ASAH_PUBLISHER_URL=http://localhost:8082
            - OSB_FARO_FRONTEND_URL=http://analytics-frontend:8080
            - OSB_ASAH_SECURITY_TOKEN=9ZPgFSdEntvRPjgRcstSgkUCBzKyjz4hbuaGbdW9h3BHcJbZLuuSqd6BpFLhRErS
            - SPRING_PROFILES_ACTIVE=prod
        image: liferay/com-liferay-osb-asah:latest-demo
        ports:
            - "8082:8080"
        volumes:
            - export:/export
            - temp:/temp
    analytics-elasticsearch:
        container_name: analytics-elasticsearch
        environment:
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - http.cors.allow-origin=*
            - http.cors.enabled=true
        healthcheck:
            interval: 10s
            retries: 3
            start_period: 5s
            test: ["CMD", "curl", "-f", "http://localhost:9200"]
            timeout: 10s
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
        ports:
            - "9200:9200"
        volumes:
            - analytics-data1:/usr/share/elasticsearch/data
    analytics-frontend:
        container_name: analytics-frontend
        environment:
            - FARO_DEFAULT_WE_DEPLOY_KEY=local.lfr.cloud
            - FARO_URL=http://localhost:8081
            - OSB_ASAH_BACKEND_URL=http://analytics-backend:8080
            - OSB_ASAH_PUBLISHER_URL=http://analytics-backend:8080
        image: liferay/com-liferay-osb-faro:latest-demo
        ports:
            - "8081:8080"
        volumes:
            - analytics-data2:/opt/liferay/data
version: "2.4"
volumes:
    analytics-data1:
        driver: local
    analytics-data2:
        driver: local
    export:
        driver: local
    temp:
        driver: local